2025/01/16 18:07:49 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231"
2025/01/16 18:07:49 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231", referrer: "http://localhost:4231/"
2025/01/16 23:29:05 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231"
2025/01/16 23:29:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231", referrer: "http://localhost:4231/"
2025/01/16 23:30:01 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231"
2025/01/16 23:30:01 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231", referrer: "http://localhost:4231/"
2025/01/16 23:39:19 [error] 22#22: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231"
2025/01/16 23:39:19 [error] 22#22: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:4231", referrer: "http://localhost:4231/"
2025/01/16 23:40:00 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:5000"
2025/01/16 23:40:00 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:5000", referrer: "http://localhost:5000/"
2025/01/16 23:43:26 [error] 23#23: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:5000"
2025/01/16 23:43:26 [error] 23#23: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.2:3031", host: "localhost:5000", referrer: "http://localhost:5000/"
2025/01/16 23:53:51 [emerg] 1#1: no port in upstream "uwsgi" in /etc/nginx/nginx.conf:45
2025/01/16 23:58:15 [crit] 22#22: *2 connect() to unix:/tmp/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:5000"
2025/01/16 23:58:15 [crit] 22#22: *2 connect() to unix:/tmp/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:5000", referrer: "http://localhost:5000/"
2025/01/16 23:58:25 [crit] 22#22: *2 connect() to unix:/tmp/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:5000"
2025/01/16 23:58:25 [crit] 22#22: *2 connect() to unix:/tmp/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:5000", referrer: "http://localhost:5000/"
2025/01/16 23:58:33 [crit] 22#22: *2 connect() to unix:/tmp/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:5000"
2025/01/16 23:58:33 [crit] 22#22: *2 connect() to unix:/tmp/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "localhost:5000", referrer: "http://localhost:5000/index"
2025/01/17 14:12:46 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 14:18:54 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 14:38:14 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 14:46:27 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 14:51:21 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 14:54:45 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 14:58:41 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 15:05:16 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 15:23:12 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 15:23:29 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
2025/01/17 15:24:46 [emerg] 1#1: duplicate location "/" in /etc/nginx/nginx.conf:57
